services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: supersecret_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        NODE_ENV: production
        PORT: 3000
        # Conexión interna usando el hostname del servicio "db"
        DATABASE_URL: postgres://appuser:${POSTGRES_PASSWORD}@db:5432/appdb
      ports:
        - "3000:3000"
      depends_on:
        db:
          condition: service_healthy
      restart: unless-stopped

volumes:
  pgdata-dev:
